# Generated by Django 4.1.1 on 2022-09-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
    ]
