# Generated by Django 4.1.1 on 2022-09-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0002_remove_usuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(max_length=200),
        ),
    ]
