# Generated by Django 4.1.1 on 2022-09-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
