# Generated by Django 4.1.1 on 2022-10-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0004_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('E', 'Empleado'), ('C', 'Cliente')], default='C', max_length=1),
        ),
    ]
