# Generated by Django 4.1.1 on 2022-10-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.IntegerField()),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_producto',
        ),
        migrations.AddField(
            model_name='citas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Vitario.usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Vitario.categoria'),
        ),
    ]
