# Generated by Django 4.1.1 on 2022-10-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0008_rename_id_categoria_categoria_codigo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='medio_pago',
            field=models.CharField(max_length=100),
        ),
    ]
