# Generated by Django 4.1.1 on 2022-10-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0010_alter_factura_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='vitario/fotos/defaultPro.png', upload_to='vitario/fotos'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='foto',
            field=models.ImageField(default='vitario/fotos/defaultMas.png', upload_to='vitario/fotos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='vitario/fotos/defaultUsu.png', upload_to='vitario/fotos'),
        ),
    ]
