# Generated by Django 3.2.12 on 2022-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0011_producto_foto_servicios_foto_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre_categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('M', 'Medicamentos'), ('A', 'Accesorios'), ('CP', 'Concentrado para perros'), ('CG', 'Concentrado para gatos'), ('AP', 'Alimentos y Premios'), ('S', 'Sin categoria')], default='S', max_length=2),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
