# Generated by Django 3.2.12 on 2022-10-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0012_auto_20221028_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='servicios',
            field=models.ForeignKey(default='Sin servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='Vitario.servicios'),
        ),
    ]
