# Generated by Django 3.2.12 on 2022-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0013_alter_factura_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('M', 'Medicamentos'), ('A', 'Accesorios'), ('C', 'Concentrado'), ('AP', 'Alimentos y Premios')], max_length=2),
        ),
    ]
