# Generated by Django 4.1.1 on 2022-12-07 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vitario', '0015_auto_20221207_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='servicio',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Vitario.usuario'),
            preserve_default=False,
        ),
    ]
